CREATE TABLE IF NOT EXISTS main_settings (
    setting_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_group VARCHAR(50) NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value LONGTEXT NULL,
    value_type ENUM('string','int','float','boolean','json','datetime') NOT NULL DEFAULT 'string',
    description TEXT NULL,
    editable TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (setting_id),
    UNIQUE KEY uk_main_settings_group_key (setting_group, setting_key),
    KEY idx_main_settings_group (setting_group),
    KEY idx_main_settings_editable (editable)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO main_settings
(setting_group, setting_key, setting_value, value_type, description, editable)
VALUES
('application','name','easyITCalendar','string','Anzeigename der Kalenderanwendung.',1),
('application','locale','de-DE','string','Sprache und Zahlen-/Datumsformat.',1),
('application','timezone','Europe/Stockholm','string','IANA-Zeitzone für Datum und Uhrzeit.',1),
('calendar','default_view','week','string','Startansicht: day, week oder month.',1),
('calendar','week_start','1','int','Erster Wochentag; 1 entspricht Montag.',1),
('calendar','slot_minutes','30','int','Dauer eines Zeitrasters in Minuten.',1),
('calendar','snap_radius_px','5','int','Snap-Radius beim Verschieben in Pixeln.',1),
('calendar','hour_start','7','int','Erste sichtbare volle Stunde.',1),
('calendar','hour_end','22','int','Letzte sichtbare volle Stunde.',1),
('calendar','show_weekends','true','boolean','Samstag und Sonntag anzeigen.',1),
('views','day','true','boolean','Tagesansicht freischalten.',1),
('views','week','true','boolean','Wochenansicht freischalten.',1),
('views','month','true','boolean','Monatsansicht freischalten.',1),
('rights','lesson_read','true','boolean','Termine lesen und darstellen.',1),
('rights','lesson_create','true','boolean','Neue Termine anlegen.',1),
('rights','lesson_edit','true','boolean','Termine bearbeiten.',1),
('rights','lesson_delete','true','boolean','Termine löschen.',1),
('rights','lesson_move','true','boolean','Termine per Drag-and-drop verschieben.',1),
('rights','block_read','true','boolean','Blockierte Bereiche darstellen.',1),
('rights','block_create','true','boolean','Bereiche blockieren.',1),
('rights','block_delete','true','boolean','Blockierungen aufheben.',1),
('rights','help_read','true','boolean','Hilfe und Handbücher anzeigen.',1),
('features','drag_drop','true','boolean','Drag-and-drop technisch aktivieren.',1),
('features','overlaps','true','boolean','Terminüberlagerungen zulassen und versetzt darstellen.',1),
('features','blocked_slots','true','boolean','Blockierbare Bereiche aktivieren.',1),
('features','block_range_drag','true','boolean','Strg + Rechtsziehen für Blockbereiche aktivieren.',1),
('features','help','true','boolean','HTML-Hilfesystem aktivieren.',1),
('features','completion_events','true','boolean','Abschlussereignisse nach Terminverschiebungen erzeugen.',1),
('features','attachments','true','boolean','Dateinamen im Feld appendizies erlauben.',1),
('colors','lesson','#2D7FF9','string','Grundfarbe aktiver Termine.',1),
('colors','lesson_inactive','#B8B8B8','string','Farbe inaktiver Termine.',1),
('colors','blocked','#C84B4B','string','Farbe blockierter Bereiche.',1),
('colors','today','#FFF5CC','string','Hervorhebung des aktuellen Tages.',1),
('colors','selection','#D6ECFF','string','Farbe der Auswahl- und Zielvorschau.',1),
('dragdrop','allow_overlap','true','boolean','Ablage auf zeitlich belegten Bereichen zulassen.',1),
('dragdrop','left_edge_snap','true','boolean','Linke Kante des Termins für die Zielerkennung verwenden.',1),
('dragdrop','show_preview','true','boolean','Zielslot während des Ziehens hervorheben.',1),
('blocking','ctrl_rightclick','true','boolean','Strg + Rechtsklick zum Umschalten eines Slots.',1),
('blocking','ctrl_drag','true','boolean','Strg + Rechtsziehen über mehrere Slots.',1),
('blocking','allow_ranges','true','boolean','Zusammenhängende Blockbereiche erlauben.',1),
('help','enabled','true','boolean','Hilfefunktion aktivieren.',1),
('help','language','de','string','Sprache des Hilfepakets.',1),
('help','start_page','index.html','string','Startseite im Hilfeordner.',1),
('attachments','enabled','true','boolean','Anlagen-Dateinamen aktivieren.',1),
('attachments','max_files','20','int','Maximale Zahl der Dateinamen je Termin.',1),
('attachments','max_size_mb','25','int','Vorgesehene maximale Dateigröße je Datei.',1),
('attachments','allowed_extensions','["pdf","doc","docx","xls","xlsx","jpg","jpeg","png","zip"]','json','Erlaubte Dateiendungen als JSON-Array.',1),
('events','default_duration','60','int','Standarddauer eines neuen Termins in Minuten.',1),
('events','minimum_duration','30','int','Kleinste zulässige Termindauer in Minuten.',1),
('events','allow_overlap','true','boolean','Zeitliche Überschneidungen erlauben.',1),
('events','generate_completion_event','true','boolean','Abschlussereignis nach erfolgreichem Verschieben erzeugen.',1)
ON DUPLICATE KEY UPDATE
setting_value=VALUES(setting_value), value_type=VALUES(value_type),
description=VALUES(description), editable=VALUES(editable);

SELECT setting_group, setting_key, setting_value, value_type, editable
FROM main_settings ORDER BY setting_group, setting_key;
